### ISSUE TITLE
Undefined function BABEL-ENCODINGS::HANDLE-ERROR

### ISSUE THREAD

**Issue by McParen** [cl-babel/babel#50]
; file: /home/user/quicklisp/dists/quicklisp/software/babel-20230214-git/src/enc-ebcdic.lisp
; in: DEFUN BABEL-ENCODINGS::EBCDIC-FI-ENCODER
;     (BABEL-ENCODINGS::HANDLE-ERROR)
; 
; caught STYLE-WARNING:
;   undefined function: BABEL-ENCODINGS::HANDLE-ERROR
; 
; compilation unit finished
;   Undefined function:
;     BABEL-ENCODINGS::HANDLE-ERROR

**Comment by atgreen** [comment]
There appears to be a fix that is over a year old: https://github.com/cl-babel/babel/pull/45
